# Generated by Django 3.1.5 on 2026-04-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_stockitem_stocklog_stockrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
